### ISSUE TITLE
Authorization token not issuing properly

### ISSUE THREAD

**Issue by nstephenh** [royendgel/django-backblazeb2-storage#13]
Whenever I try to do an upload, I get the following error:
AttributeError at /admin/shop/difiles/add/
'BackBlazeB2' object has no attribute 'authorization_token'
Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/admin/shop/difiles/add/

Django Version: 3.0.3
Python Version: 3.7.3
Installed Applications:
[...
 'social_django',
 'b2_storage',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1081, in save_model
    obj.save()
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1383, in execute_sql
    for sql, params in self.as_sql():
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1328, in as_sql
    for obj in self.query.objs
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1328, in <listcomp>
    for obj in self.query.objs
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1327, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1278, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/fields/files.py", line 288, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/fields/files.py", line 86, in save
    name = self.field.generate_filename(self.instance, name)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/fields/files.py", line 307, in generate_filename
    return self.storage.generate_filename(filename)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/core/files/storage.py", line 364, in _setup
    self._wrapped = get_storage_class()()
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2_storage/storage.py", line 22, in __init__
    self.b2 = BackBlazeB2(**kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2_storage/backblaze_b2.py", line 16, in __init__
    self.get_bucket_id_by_name()
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2_storage/backblaze_b2.py", line 86, in get_bucket_id_by_name
    headers = {'Authorization': self.authorization_token}

Exception Type: AttributeError at /admin/shop/difiles/add/
Exception Value: 'BackBlazeB2' object has no attribute 'authorization_token'

**Comment by nstephenh** [comment]
Upon closer inspection, my key and key_id were backwards, but not reversed in my .env file. Apparently I was setting them backwards in my IDE. User error strikes again.
