### ISSUE TITLE
Error on upload after installing 

### ISSUE THREAD

**Issue by grf1** [royendgel/django-backblazeb2-storage#2]
Getting this error upon installing the package and trying to upload a file. 

`Traceback (most recent call last):
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/framework_django.py", line 497, in wrapper return wrapped(*args, **kwargs)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view return self.dispatch(request, *args, **kwargs)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/component_djangorestframework.py", line 27, in _nr_wrapper_APIView_dispatch_ return wrapped(*args, **kwargs)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view return view_func(*args, **kwargs)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch response = self.handle_exception(exc)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch response = handler(request, *args, **kwargs)
File "/root/virtual/nimbus/Nimbus/nimbus/apps/api/views.py", line 57, in post media_item.save()
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save force_update=force_update, update_fields=update_fields)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert using=using, raw=raw)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert return insert_query(self.model, objs, fields, **kwargs)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/query.py", line 1511, in insert_query return query.get_compiler(using=using).execute_sql(return_id)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 897, in execute_sql for sql, params in self.as_sql():
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 855, in as_sql for obj in self.query.objs
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 252, in pre_save file.save(file.name, file, save=False)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 86, in save self.name = self.storage.save(name, content)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/utils/functional.py", line 213, in inner self._setup()
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/core/files/storage.py", line 286, in _setup self._wrapped = get_storage_class()()
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/core/files/storage.py", line 282, in get_storage_class return import_by_path(import_path or settings.DEFAULT_FILE_STORAGE)
File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path error_prefix, module_path, class_name))
ImproperlyConfigured: Module "b2_storage" does not define a "B2Storage" attribute/class`

**Comment by royendgel** [comment]
Hi, 
are you using it as your DEFAULT FILE STORAGE? if so please change this setting in your django : `DEFAULT_FILE_STORAGE = 'b2_storage.storage.B2Storage'`
let me know.

I need to update this repo.. ;)

**Comment by grf1** [comment]
Hi, updated that line in my settings. The file is uploading to B2, however I'm getting this error on uploading a file..

  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/framework_django.py", line 497, in wrapper
    return wrapped(_args, *_kwargs)
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/component_djangorestframework.py", line 27, in _nr_wrapper_APIView_dispatch_
    return wrapped(_args, *_kwargs)
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(_args, *_kwargs)
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, _args, *_kwargs)
  File "/root/virtual/nimbus/Nimbus/nimbus/apps/api/views.py", line 62, in post
    data = ViewCreatedFileSerializer(media_item).data
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 575, in data
    self._data = self.to_native(obj)
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 351, in to_native
    value = field.field_to_native(obj, field_name)
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/rest_framework/fields.py", line 1035, in field_to_native
    value = getattr(self.parent, self.method_name)(obj)
  File "/root/virtual/nimbus/Nimbus/nimbus/apps/media/serializers.py", line 46, in get_target_file_url
    return _get_target_file_url(obj)
  File "/root/virtual/nimbus/Nimbus/nimbus/apps/media/serializers.py", line 8, in _get_target_file_url
    return obj.raw_url
  File "/root/virtual/nimbus/Nimbus/nimbus/apps/media/models.py", line 89, in raw_url
    return self.target_file.storage.url(self.target_file.name)
  File "/root/virtual/nimbus/local/lib/python2.7/site-packages/django/core/files/storage.py", line 121, in url
    raise NotImplementedError()
NotImplementedError

Thanks for the help :)

**Comment by royendgel** [comment]
That error is because the url method is not implemented. 
the methods implemented are : save and open. 

see the storage.py
